### PR TITLE
Add debug tool for helping inference and checker-framework extract min test case.

### PR DESCRIPTION
**Pull request by CharlesZ-Chen**
Add a new debug tool for help CFI and CF extracting  ***local*** 1-minimum test vase from target project that exposes a bug in CF/CFI.

Changes:

- Add `infer-debug.py`: code for new debug tool
- Adapt `tools/__init__.py`, `tools/check.py`, and `tools/infer.py` for this new feature.

### CODE REVIEW

**Comment by CharlesZ-Chen** [comment]
@topnessman @topnessman Just had an update on this debug tool:

I changed the algorithm from bottom-top to top-down by using delta debugging (As after reading through delta debugging I realized it has better time complexity of finding the minimized test case).

I had a local test on this update, and it seems works to me.

Feel free to pull in this update, and do let me know if there were problems when you using it!

**Comment by CharlesZ-Chen** [comment]
@topnessman Currently is finding the minimum file set. I think it is also possible to minimized the file itself by delta debugging.

I just found a tool [Lithium](https://github.com/MozillaSecurity/lithium) used in Mozilla to minimized their test case (on file level, not the set level).

So I'm just looking if we can use this tool directly or we need our own implementation on file level.

Will update my investigation.

**Comment by CharlesZ-Chen** [comment]
@topnessman @wmdietl Another update:

Finally it supports on minimizing file itself!

I tried on my machine, and it founds a file trigger the crash, and reduced it from 600+ lines to 35 lines.

The only problem here is the performance is not quite good --- for above file, it takes around 20+ mins to finish.

I think currently the reason of bad performance is because I minimizing file on line level, which creates a lot of temp files that even cannot compile. Maybe if we could change the atomic unit to AST level might achieve much better performance, but this is somehow a huge work....

To use this new feature, it requires `Lithium` installed as a pip package:
```bash
git clone https://github.com/MozillaSecurity/lithium.git
cd lithium
python setup.py install
```

Feel free to try this new feature, and do let me know if you have any comments!
```

**Comment by wmdietl** [comment]
I pushed some tiny tweaks to wording.
Can you add a README to explain how to use the tool?
Is `infer_debug.py` a good name, as it can be used for both `infer` and `check`? Would `testminimizer` or something be better?

**Comment by CharlesZ-Chen** [comment]
Thanks for polishing the README! I've added a section about dependencies of TestMinimizer. It would be better to automate the process of installing `Lithum` for users. I will automate this process, and then merge this PR.

**Comment by wmdietl** [comment]
I think it's ok to manually install Lithium. The Checker Framework also has to be installed first.

**Pull request merged**
